### PR TITLE
Mono

### PR DESCRIPTION
**Pull request by chmorgan**
Add support for mono mp3s, adjust mp3s to mono to reduce their size, trim size of spiffs partition by 50%, reduces already very long programming time by a few minutes.

Tested here on eep-box hardware. Let me know if there is any feedback, questions etc.

### CODE REVIEW

**Comment by alic-maker** [comment]
Thank you for your contribution! There will be some tests today.

**Comment by chmorgan** [comment]
Hi @alic-maker thoughts on this PR?

**Comment by TDA-2030** [comment]
It looks good and will be merged in near future.

**Comment by chmorgan** [comment]
@TDA-2030 I'm close to having something ready for the audio component refactor. This PR does overlap with that change though. Possible to get this one merged in in the nearish future? If there are any changes requested I'm available to discuss or adjust.

**Comment by TDA-2030** [comment]
It should be merged in the near future, but I don't have permission to merge.

**Pull request closed without merging**
