### PR TITLE
Support to build against ESP-IDF v5.0-dev

### PR DESCRIPTION
**Pull request by mahavirj**
- Changes are backward compatible with ESP-IDF v4.4 release
- Have tested functionality of `factory_demo` with this PR

### CODE REVIEW

**Comment by alic-maker** [comment]
Thank you for your contribution. We still need more tests for this PR, especially for the speech recognition part, which will take some time.

**Comment by igrr** [comment]
@alic-maker gentle ping, could you please revisit the PR?

I don't think doing complete test should be a blocker for merging this. At the moment, IDF release/v5.0 branch can't be used to build this project, at all. After the PR is merged, the demo app will be at least buildable, so that's already an improvement. If you need to do any fix for the speech recognition part, you can do this in a follow-up MR or PR.

**Comment by alic-maker** [comment]
Now this [mahavirj:feature/support_esp_idf_v5.0-dev](https://github.com/mahavirj/esp-box/tree/feature/support_esp_idf_v5.0-dev) branch will fail to compile with IDF release/v5.0. I changed Rainmaker to master, and it seems that the compilation will still fail.

**Comment by mahavirj** [comment]
> Now this [mahavirj:feature/support_esp_idf_v5.0-dev](https://github.com/mahavirj/esp-box/tree/feature/support_esp_idf_v5.0-dev) branch will fail to compile with IDF release/v5.0. I changed Rainmaker to master, and it seems that the compilation will still fail.

@alic-maker I will update this PR to fix the build problems with latest `release/v5.0` branch

**Comment by mahavirj** [comment]
@alic-maker Please check the latest changes here, PR makes all examples compatible with ESP-IDF 5.x release. Please note that there are still some warnings about deprecated fields but that requires some driver level changes, so we can take them up in followup PRs.

**Comment by espressif2022** [comment]
@mahavirj ,hello
I tried to merge the RP code and found that the factory_demo could not build successfully；“ERROR: Cannot process component requirements.  Multiple candidates to led_strip”
I clone the original https://github.com/mahavirj/esp-box.git, branch:feature/support_esp_idf_v5.0-dev， it's the same;

And there are many build warnnings,  will there be a follow-up PR to fix this?

**Pull request closed without merging**
